# Generated by Django 3.1.2 on 2021-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pincode', models.PositiveIntegerField(max_length=8)),
            ],
        ),
    ]
