# Generated by Django 3.1.2 on 2021-05-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C_Docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='pincode',
        ),
    ]
