# Generated by Django 3.1.2 on 2021-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_Docs', '0002_remove_notification_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pincode',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
