# Generated by Django 3.1.2 on 2021-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_Docs', '0003_notification_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
